# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import object_storage_pb2 as object__storage__pb2


class ObjectStorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Authenticate = channel.unary_unary(
                '/object_storage.ObjectStorageService/Authenticate',
                request_serializer=object__storage__pb2.AuthenticationRequest.SerializeToString,
                response_deserializer=object__storage__pb2.AuthenticationResponse.FromString,
                )
        self.UploadObject = channel.unary_unary(
                '/object_storage.ObjectStorageService/UploadObject',
                request_serializer=object__storage__pb2.UploadObjectRequest.SerializeToString,
                response_deserializer=object__storage__pb2.UploadObjectResponse.FromString,
                )
        self.GetObject = channel.unary_unary(
                '/object_storage.ObjectStorageService/GetObject',
                request_serializer=object__storage__pb2.GetObjectRequest.SerializeToString,
                response_deserializer=object__storage__pb2.GetObjectResponse.FromString,
                )
        self.ListObjects = channel.unary_unary(
                '/object_storage.ObjectStorageService/ListObjects',
                request_serializer=object__storage__pb2.ListObjectsRequest.SerializeToString,
                response_deserializer=object__storage__pb2.ListObjectsResponse.FromString,
                )
        self.DeleteObject = channel.unary_unary(
                '/object_storage.ObjectStorageService/DeleteObject',
                request_serializer=object__storage__pb2.DeleteObjectRequest.SerializeToString,
                response_deserializer=object__storage__pb2.DeleteObjectResponse.FromString,
                )
        self.ListUserBuckets = channel.unary_unary(
                '/object_storage.ObjectStorageService/ListUserBuckets',
                request_serializer=object__storage__pb2.ListUserBucketsRequest.SerializeToString,
                response_deserializer=object__storage__pb2.ListUserBucketsResponse.FromString,
                )


class ObjectStorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Authenticate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListObjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserBuckets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Authenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.Authenticate,
                    request_deserializer=object__storage__pb2.AuthenticationRequest.FromString,
                    response_serializer=object__storage__pb2.AuthenticationResponse.SerializeToString,
            ),
            'UploadObject': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadObject,
                    request_deserializer=object__storage__pb2.UploadObjectRequest.FromString,
                    response_serializer=object__storage__pb2.UploadObjectResponse.SerializeToString,
            ),
            'GetObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObject,
                    request_deserializer=object__storage__pb2.GetObjectRequest.FromString,
                    response_serializer=object__storage__pb2.GetObjectResponse.SerializeToString,
            ),
            'ListObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListObjects,
                    request_deserializer=object__storage__pb2.ListObjectsRequest.FromString,
                    response_serializer=object__storage__pb2.ListObjectsResponse.SerializeToString,
            ),
            'DeleteObject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteObject,
                    request_deserializer=object__storage__pb2.DeleteObjectRequest.FromString,
                    response_serializer=object__storage__pb2.DeleteObjectResponse.SerializeToString,
            ),
            'ListUserBuckets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserBuckets,
                    request_deserializer=object__storage__pb2.ListUserBucketsRequest.FromString,
                    response_serializer=object__storage__pb2.ListUserBucketsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'object_storage.ObjectStorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ObjectStorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Authenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/object_storage.ObjectStorageService/Authenticate',
            object__storage__pb2.AuthenticationRequest.SerializeToString,
            object__storage__pb2.AuthenticationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/object_storage.ObjectStorageService/UploadObject',
            object__storage__pb2.UploadObjectRequest.SerializeToString,
            object__storage__pb2.UploadObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/object_storage.ObjectStorageService/GetObject',
            object__storage__pb2.GetObjectRequest.SerializeToString,
            object__storage__pb2.GetObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/object_storage.ObjectStorageService/ListObjects',
            object__storage__pb2.ListObjectsRequest.SerializeToString,
            object__storage__pb2.ListObjectsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/object_storage.ObjectStorageService/DeleteObject',
            object__storage__pb2.DeleteObjectRequest.SerializeToString,
            object__storage__pb2.DeleteObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListUserBuckets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/object_storage.ObjectStorageService/ListUserBuckets',
            object__storage__pb2.ListUserBucketsRequest.SerializeToString,
            object__storage__pb2.ListUserBucketsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
